name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v4
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
      - name: Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: composer install -o
      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1
      - name: Run tests
        run: composer run-script phpunit-ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
